### ISSUE TITLE
Login doesn't work

### ISSUE THREAD

**Issue by sollidius** [Ne00n/Prometheus#38]
Followed instructions to install.
But when going to index.php i get:

Please Sign In
prepare() failed: Table 'prometheus_db.blacklist' doesn't exist

Forgot something in the .sql perhaps?

**Comment by Ne00n** [comment]
The SQL is actually a dump from my test server, it should work fine.
Did you tried to copy paste it and put it into SQL exec directly?

**Comment by Ne00n** [comment]
He got it fixed, seems to be the import vent wrong.
