### ISSUE TITLE
Keine Weiterleitung nach Login

### ISSUE THREAD

**Issue by ql700** [Ne00n/Prometheus#48]
Nachdem ich mich eingeloggt habe, passiert leider überhaupt nichts.
Wenn ich versuche die Seiten manuell aufzurufen nachdem ich mich eingeloggt habe. bsp: www.domain.de/panel/pages/addons.php bekomme ich folgende Fehlermeldung: Fatal error: Call to a member function prepare() on a non-object in panel/pages/addons.php on line 7

Vielen Dank
MfG

**Comment by Ne00n** [comment]
SQL File importiert?
Entweder du bekommst eine Fehlermeldung wegen Falschen Login oder du wirst weitergeleitet.
PHP 5.6 is das minimum, da sonst der Login nicht funktioniert > http://php.net/manual/de/function.password-verify.php

Direkt aufrufen geht nicht, da die Index.php die functions.php includiert für die mysqli verbindung und die addons.php das nicht alleine tuht. Weshalb der Fehler kommt. Habe jetzt kurz ein Update gepusht der eine Automatische Weiterleitung auf die Login seite erledigt.

**Comment by ql700** [comment]
Ich bekomme immer diese Fehlermeldungen: Unknown error type: [2] session_start() [<a href='http://de.php.net/function.session-start'>function.session-start</a>]: Cannot send session cookie - headers already sent by (output started at /pages/header.php:19) at /pages/login.php in Line 42

Unknown error type: [2] Cannot modify header information - headers already sent by (output started at /pages/header.php:19) at /pages/login.php in Line 45

**Comment by Ne00n** [comment]
Versuch mal eben das Update was ich gepusht habe.

**Comment by ql700** [comment]
Ok, Vielen Dank.
Jetzt bekomme ich nur noch diese Fehlermeldung: Unknown error type: [2] Cannot modify header information - headers already sent by (output started at /pages/header.php:17) at /pages/login.php in Line 44

**Comment by Ne00n** [comment]
Ich hatte diese Fehler nie bei meiner Testinstallation, habe sollte jetzt mit den Update #206 komplett gefixt sein.

**Comment by ql700** [comment]
Funktioniert jetzt, einbahnfrei. Vielen Dank.
Was muss hier eingetragen werden, wenn ich einen Rootserver hinzufüge?: https://i.gyazo.com/1cb603690853bef49447f1597609f8a5.png

**Comment by Ne00n** [comment]
Ja, je nachdem ob der Rootserver SSD's hatt usw läuft die installation schnell ab, Bei Droplets auf DigitalOcean.com geht das in ca 20sec.
